// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkrvtretjsihegwsocnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcnZ0cmV0anNpaGVnd3NvY251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNTExMzMsImV4cCI6MjA1MjgyNzEzM30.2-BzxqRhsmZYf89lodkmhYJ6eW_vlZlygMi8K2xsYfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);